# -*- coding: utf-8 -*-
"""128/.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woo-Es4WqaBQiY4DgL1UMtwSkz3L-y1s
"""

#Introducing System Administration with Python
import os
# Run the Bash command "ls" using os.system()
os.system("ls")

import subprocess
# Run the Bash command "ls" using subprocess.run()
subprocess.run(["ls"])

import subprocess
# Run the Bash command "ls -l" using subprocess.run()
subprocess.run(["ls", "-l"])

import subprocess
# Run the Bash command "uname -a" using subprocess.run()
command = "uname"
command_argument = "-a"
print(f'Gathering system information with command: {command} {command_argument}')
subprocess.run([command, command_argument])

import subprocess
# Run the Bash command "ps -x" using subprocess.run()
command = "ps"
command_argument = "-x"
print(f'Gathering active process information with command: {command} {command_argument}')
subprocess.run([command, command_argument])

import subprocess
# Run the Bash command "ps -x" using subprocess.run()
command = "ps"
command_argument = "-x"
print(f'Gathering active process information with command: {command} {command_argument}')
subprocess.run([command, command_argument])

