# -*- coding: utf-8 -*-
"""jsonFileHandler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woo-Es4WqaBQiY4DgL1UMtwSkz3L-y1s
"""

import json

def readJsonFile(fileName):
    data = ""
    try:
        with open(fileName) as json_file:
            data = json.load(json_file)
    except IOError:
        print("Could not read file")
    return data